spring:
  application.name: gateway-server
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: feed_service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
        - id: chat_service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 8765
