spring:

  application.name: gateway-server

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5000"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: discovery-server
          uri: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}
          predicates:
            - Path=/eureka/**
        - id: user-service
          uri: lb://${USER_SERVICE_HOST}
          predicates:
            - Path=/api/v1/user/**
        - id: feed-service
          uri: lb://${FEED_SERVICE_HOST}
          predicates:
            - Path=/api/v1/feed/**
        - id: chat-service
          uri: lb://${CHAT_SERVICE_HOST}
          predicates:
            - Path=/api/v1/chat/**
        - id: dummy-service
          uri: lb://${DUMMY_SERVICE_HOST}
          predicates:
            - Path=/api/v1/dummy/**
        - id: authorization-service
          uri: lb://${AUTH_SERVICE_HOST}
          predicates:
            - Path=/auth/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: ${GATEWAY_SERVER_PORT}
