spring:

  application.name: gateway-server

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: feed_service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
        - id: chat_service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
        - id: dummy-service
          uri: lb://dummy-service
          predicates:
            - Path=/api/dummy/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: ${GATEWAY_SERVER_PORT}
