spring:

  application:
    name: notification-service

  data:
    mongodb:
      database: ${DB_NAME}
      uri: mongodb://${DB_ROOT_USERNAME}:${DB_ROOT_PASSWORD}@${NOTIFICATION_DB_HOST:localhost}:${NOTIFICATION_DB_PORT}/${DB_NAME}?authSource=admin
      replica-set-name: ${MONGO_REPLICA_SET_NAME}

  kafka:
    bootstrap-servers: localhost:${KAFKA_BROKER_PORT}
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: message_sent_event:com.jellybrains.quietspace_backend_ms.notification_service.event.MessageSentEvent
      group-id: notificationId

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT}/eureka

server:
  port: ${NOTIFICATION_SERVICE_PORT}
