spring:
  application.name: notification-service
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}

  data:
    mongodb:
      database: ${DB_NAME}
      host: localhost
      port: ${NOTIFICATION_DB_PORT}
      username: ${DB_ROOT_USERNAME}
      password: ${DB_ROOT_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

values:
  gateway:
    url: ${GATEWAY_URL}

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG

server:
  port: ${NOTIFICATION_SERVICE_PORT}
