spring:

  application:
    name: notification-service

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  data:
    mongodb:
      database: ${DB_NAME}
      uri: ${NOTIFICATION_DB_URI}
      replica-set-name: ${MONGO_REPLICASET_NAME}

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type:
              mapping: new_message_event:com.jellybrains.quietspace_backend_ms.notification_service.event.NewMessageEvent
      group-id: notificationId

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${NOTIFICATION_SERVICE_PORT}
