global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${USER_SERVICE_HOST}:${USER_SERVICE_PORT}' ]

  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${CHAT_SERVICE_HOST}:${CHAT_SERVICE_PORT}' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}' ]

  - job_name: 'common-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${COMMON_SERVICE_HOST}:${COMMON_SERVICE_PORT}' ]

  - job_name: 'feed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${FEED_SERVICE_HOST}:${FEED_SERVICE_PORT}' ]

  - job_name: 'reaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${REACTION_SERVICE_HOST}:${REACTION_SERVICE_PORT}' ]

  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${GATEWAY_SERVER_HOST}:${GATEWAY_SERVER_PORT}' ]

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${DISCOVERY_SERVER_HOST}:${DISCOVERY_SERVER_PORT}' ]

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}' ]

