version: '3.8'
services:

  user-service-db:
    container_name: ${USER_DB_HOST}
    hostname: ${USER_DB_HOST}
    image: mongo:5.0
    volumes:
      - user-data:/data/db
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    ports:
      - ${EXP_USER_DB_PORT}:${USER_DB_PORT}
    expose:
      - ${USER_DB_PORT}

  chat-service-db:
    container_name: ${CHAT_DB_HOST}
    hostname: ${CHAT_DB_HOST}
    image: postgres
    volumes:
      - chat-data:/data/postgres
    environment:
      POSTGRES_DB: ${CHAT_DB_HOST}
      POSTGRES_USER: ${DB_USER_USERNAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - ${EXP_CHAT_DB_PORT}:${CHAT_DB_PORT}
    expose:
      - ${CHAT_DB_PORT}
    command: -p ${EXP_CHAT_DB_PORT}
    restart: on-failure

  feed-service-db:
    container_name: ${FEED_DB_HOST}
    hostname: ${FEED_DB_HOST}
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - feed-data:/var/lib/mysql
    ports:
      - ${EXP_FEED_DB_PORT}:${FEED_DB_PORT}

  notification-service-db:
    container_name: ${NOTIFICATION_DB_HOST}
    hostname: ${NOTIFICATION_DB_HOST}
    image: mongo:5.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    ports:
      - ${EXP_NOTIFICATION_DB_PORT}:${NOTIFICATION_DB_PORT}
    volumes:
      - notification-data:/data/db

  keycloak-db:
    container_name: ${KEYCLOAK_DB_HOST}
    hostname: ${KEYCLOAK_DB_HOST}
    image: mysql:5.7
    restart: on-failure
    volumes:
      - keycloak-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

  keycloak:
    container_name: ${KEYCLOAK_HOST}
    hostname: ${KEYCLOAK_HOST}
    image: quay.io/keycloak/keycloak:24.0.3
    restart: on-failure
    volumes:
      - realms-data/:/opt/keycloak/data/import/
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      - keycloak-db

  zookeeper:
    container_name: ${ZOOKEEPER_HOST}
    hostname: ${ZOOKEEPER_HOST}
    image: confluentinc/cp-zookeeper:7.0.1
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}

  broker:
    container_name: ${KAFKA_BROKER_HOST}
    hostname: ${KAFKA_BROKER_HOST}
    image: confluentinc/cp-kafka:7.0.1
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_CLIENT_PORT}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_BROKER_PORT},PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - ${KAFKA_BROKER_PORT}:${KAFKA_BROKER_PORT}
    depends_on:
      - zookeeper

volumes:
  feed-data:
  keycloak-data:
  chat-data:
  user_data:
  notification-data: