version: '3.8'
services:

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:discovery-server
    container_name: quietspace-discovery-server
    env_file:
      - .env
    networks:
      - microservices-net
    ports:
      - ${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}

  config-server:
    build:
      context: ./config-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:config-server
    container_name: quietspace-config-server
    env_file:
      - .env
    depends_on:
      - discovery-server
    networks:
      - microservices-net
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:gateway-server
    container_name: quietspace-gateway-server
    env_file:
      - .env
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    ports:
      - ${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}

  feed-service:
    build:
      context: ./feed-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:feed-service
    container_name: quietspace-feed-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${FEED_SERVICE_PORT}:${FEED_SERVICE_PORT}

  chat-service:
    build:
      context: ./chat-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:chat-service
    container_name: quietspace-chat-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}

  dummy-service:
    build:
      context: ./dummy-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:dummy-service
    container_name: quietspace-dummy-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${DUMMY_SERVICE_PORT}:${DUMMY_SERVICE_PORT}

  notification-service:
    build:
      context: ./notification-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:notification-service
    container_name: quietspace-notification-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}

  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:user-service
    container_name: quietspace-user-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${USER_SERVER_PORT}:${USER_SERVER_PORT}

networks:
  microservices-net:
    name: microservices-net
    driver: bridge