spring:

  application:
    name: authorization-service
    mailing:
      frontend:
        activation-url: ${ACTIVATION_URL}
    mail:
      host: ${MAILDEV_HOST}
      port: ${MAILDEV_PORT}
      username: thural
      password: thural
      properties:
        mail:
          smtp:
            trust: "*"
            auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 600000 # 10 minutes
        refresh-token:
          expiration: 86400000 # one day

  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}

  mail:
    host: ${MAILDEV_HOST}
    port: ${MAILDEV_PORT}
    username: thural
    password: thural
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  datasource:
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
    url: jdbc:mysql://localhost:${AUTH_DB_PORT}/quietspace
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${AUTH_SERVICE_PORT}
