spring:

  application:
    name: dummy-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${DUMMY_SERVICE_PORT}