spring:
  application:
    name: dummy-service
  cloud:
    config:
      uri: http://localhost:8899

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  timelimiter:
    instances:
      dummy:
        timeout-duration: 3s
  circuitbreaker:
    instances:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      dummy:
        max-attempts: 3
        wait-duration: 5s

server:
  port: 8888