version: '3.8'
services:

  auth-service-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user-data:/data/db
    restart: on-failure
    networks:
      - microservices-net
    ports:
      - ${AUTH_DB_PORT}:3306
    expose:
      - 3306

  user-service-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user-data:/data/db
    restart: on-failure
    networks:
      - microservices-net
    ports:
      - ${USER_DB_PORT}:3306
    expose:
      - 3306

  chat-service-db:
    image: postgres
    volumes:
      - chat-data:/data/postgres
    environment:
      POSTGRES_DB: ${CHAT_DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - microservices-net
    ports:
      - ${CHAT_DB_PORT}:5432
    expose:
      - 5432
    command: -p ${CHAT_DB_PORT}
    restart: on-failure

  feed-service-db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - feed-data:/var/lib/mysql
    networks:
      - microservices-net
    ports:
      - ${FEED_DB_PORT}:3306

  notification-service-db:
    image: mongo:5.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICASET_NAME: ${MONGO_REPLICASET_NAME}
    networks:
      - microservices-net
    ports:
      - ${NOTIFICATION_DB_PORT}:27017
    volumes:
      - notification-data:/data/db

  reaction-service-db:
    image: mongo:5.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICASET_NAME: ${MONGO_REPLICASET_NAME}
    networks:
      - microservices-net
    ports:
      - ${REACTION_DB_PORT}:27017
    volumes:
      - reaction-data:/data/db

networks:
  microservices-net:
    name: microservices-net
    driver: bridge
    external: true

volumes:
  feed-data:
  chat-data:
  user-data:
  notification-data:
  reaction-data: