version: '3.8'
services:

  config-server:
    container_name: config-server
    build:
      context: /config-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:config-server
    env_file:
      - .env
    networks:
      - microservices-net
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}

  discovery-server:
    container_name: discovery-server
    build:
      context: /discovery-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:discovery-server
    env_file:
      - .env
    networks:
      - microservices-net
    depends_on:
      - config-server
    ports:
      - ${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}

  gateway-server:
    container_name: gateway-server
    build:
      context: /gateway-server
      dockerfile: ./Dockerfile
    image: thural/quietspace:gateway-server
    env_file:
      - .env
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    ports:
      - ${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}

  auth-service:
    container_name: auth-service
    build:
      context: /auth-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:auth-service
    env_file:
      - .env
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
    networks:
      - microservices-net
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}

  feed-service:
    container_name: feed-service
    build:
      context: /feed-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:feed-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${FEED_SERVICE_PORT}:${FEED_SERVICE_PORT}

  chat-service:
    container_name: chat-service
    build:
      context: /chat-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:chat-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}

  notification-service:
    container_name: notification-service
    build:
      context: /notification-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:notification-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}

  reaction-service:
    container_name: reaction-service
    build:
      context: /reaction-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:reaction-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${REACTION_SERVICE_PORT}:${REACTION_SERVICE_PORT}

  user-service:
    container_name: user-service
    build:
      context: /user-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:user-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}

  common-service:
    container_name: common-service
    build:
      context: /common-service
      dockerfile: ./Dockerfile
    image: thural/quietspace:common-service
    env_file:
      - .env
    depends_on:
      - config-server
    networks:
      - microservices-net
    ports:
      - ${COMMON_SERVICE_PORT}:${COMMON_SERVICE_PORT}

networks:
  microservices-net:
    name: microservices-net
    driver: bridge