version: '3.8'
services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - ${ZIPKIN_PORT}:9411
    environment:
      - STORAGE_TYPE=mem

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - microservices-net
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

networks:
  microservices-net:
    driver: bridge