spring:

  application:
    name: user-service

    urls:
      frontend: "http://localhost:5000"

    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 600000 # 10 minutes
        refresh-token:
          expiration: 86400000 # one day

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${USER_DB_URI}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${USER_SERVICE_PORT}