spring:

  application:
    name: user-service

  config:
    import: configserver:${CONFIG_URI:http://localhost:8899/config-server}
  profiles:
    active:
      - ${CONFIG_ACTIVE_PROFILE}

  data:
    mongodb:
      database: ${DB_NAME}
      uri: ${USER_DB_URI}
      replica-set-name: ${MONGO_REPLICA_SET_NAME}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server:
  port: ${USER_SERVER_PORT}