spring:
  application:
    name: user-service
  data:
    mongodb:
      database: ${DB_NAME}
      uri: mongodb://${DB_ROOT_USERNAME}:${DB_ROOT_PASSWORD}@${USER_DB_HOST:localhost}:${USER_DB_PORT}/${DB_NAME}?authSource=admin
      replica-set-name: ${MONGO_REPLICA_SET_NAME}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT}/eureka

server:
  port: ${USER_SERVER_PORT}