spring:
  application.name: feed-service
  datasource:
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
    url: jdbc:mysql://${FEED_DB_HOST:localhost}:${FEED_DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server.port: ${FEED_SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT}/eureka