spring:
  application.name: feed-service
  datasource:
    username: root
    password: @dolphin888
    url: jdbc:mysql://localhost:3306/feed
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server.port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka