spring:
  application.name: discovery-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${DISCOVERY_SERVER_PORT}/eureka
  instance:
    hostname: localhost

server:
  port: ${DISCOVERY_SERVER_PORT}
