spring:

  application.name: discovery-server

  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${DISCOVERY_SERVER_HOST:localhost}

server:
  port: ${DISCOVERY_SERVER_PORT:8761}
