spring:

  application.name: chat-service

  r2dbc:
    url: r2dbc:postgresql://${CHAT_DB_HOST:localhost}:${CHAT_DB_PORT}/chat
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:${KAFKA_BROKER_PORT}
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: message_sent_event:com.jellybrains.quietspace_backend_ms.chatservice.event.MessageSentEvent

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT}/eureka

server:
  port: ${CHAT_SERVICE_PORT}