spring:
  application:
    urls:
      gateway: ${GATEWAY_URL}
      frontend: http://${FRONTEND_HOST}:${FRONTEND_PORT}
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 6000000
        refresh-token.expiration: 86400000
    mailing:
      frontend:
        activation-url: ${ACTIVATION_URL}
  profiles:
    default: default
    active:
      - ${CONFIG_ACTIVE_PROFILE}
  cloud:
    config:
      override-system-properties: false

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-user-group-id
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'

    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: false

kafka:
  topics:
    notification: notification-topic
    profile:
      creation: profile-creation-topic
      creation-failed: profile-creation-failed-topic
      deletion: profile-deletion-topic
      deletion-failed: profile-deletion-failed-topic
      update: profile-update-topic
      update-failed: profile-update-failed-topic
    user:
      creation: user-creation-topic
      creation-failed: user-creation-failed-topic
      deletion: user-deletion-topic
      deletion-failed: user-deletion-failed-topic
      update: user-update-event
      update-failed: user-update-failed-topic
    chat:
      request:
        send: chat-request-send-topic
        delete: chat-request-delete-topic
        seen: chat-request-seen-topic
        leave: chat-request-leave-topic
        join: chat-request-join-topic
      event:
        send: chat-event-send-topic
        delete: chat-event-delete-topic
        seen: chat-event-seen-topic
        leave: chat-event-leave-topic
        join: chat-event-join-topic
        error: chat-event-error-topic

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}