spring:
  component-scan:
    base-packages:
      - com.jellybrains.quietspace.common_service.webclient
      - com.jellybrains.quietspace.common_service.security
      - com.jellybrains.quietspace.common_service.exception
      - com.jellybrains.quietspace.common_service.kafka.config
      - com.jellybrains.quietspace.chat_service

  r2dbc:
    url: ${CHAT_DB_URI}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server.port: ${CHAT_SERVICE_PORT}