spring:

  r2dbc:
    url: ${CHAT_DB_URI}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server.port: ${CHAT_SERVICE_PORT}