spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:${NOTIFICATION_DB_PORT}/${DB_NAME}?authSource=admin
      database: ${DB_NAME}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit.listener: DEBUG

server.port: ${COMMON_SERVICE_PORT}
