spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:${NOTIFICATION_DB_PORT}/${DB_NAME}
  #      database: ${DB_NAME}
  #      host: localhost
  #      port: ${NOTIFICATION_DB_PORT}
  #      username: ${DB_ROOT_USERNAME}
  #      password: ${DB_ROOT_PASSWORD}
  #      auto-index-creation: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server.port: ${COMMON_SERVICE_PORT}
