spring:
  component-scan:
    base-packages:
      - com.jellybrains.quietspace.common_service.webclient
      - com.jellybrains.quietspace.common_service.security
      - com.jellybrains.quietspace.common_service.exception
      - com.jellybrains.quietspace.common_service.kafka.config
      - com.jellybrains.quietspace.feed_service

  r2dbc:
    url: ${FEED_DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.messaging: INFO
    org.hibernate.orm.jdbc.bind: ERROR
    org.springframework.security: ERROR
    org.springframework.web: INFO
    org.hibernate.sql: ERROR
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: INFO

server.port: ${FEED_SERVICE_PORT}