spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:${REACTION_DB_PORT}/${DB_NAME}?authSource=admin

mongodb:
  transactionEnabled: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG

server.port: ${REACTION_SERVICE_PORT}