spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:${REACTION_DB_PORT}/${DB_NAME}?authSource=admin

mongodb:
  transactionEnabled: true

logging:
  level:
    root: INFO
    org.springframework.web: TRACE

server.port: ${REACTION_SERVICE_PORT}