spring:
  component-scan:
    base-packages:
      - com.jellybrains.quietspace.common_service.webclient
      - com.jellybrains.quietspace.common_service.security
      - com.jellybrains.quietspace.common_service.exception
      - com.jellybrains.quietspace.common_service.kafka.config
      - com.jellybrains.quietspace.common_service.kafka.producer
      - com.jellybrains.quietspace.user-service

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${USER_DB_URI}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.transaction: INFO
    org.springframework.orm.jpa: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO

server.port: ${USER_SERVICE_PORT}