spring:

  application.name: config-server

  cloud.config.server.prefix: /config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GITHUB_URI}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PAT}
          clone-on-start: true
          timeout: 10
          skip-ssl-validation: true
          search-paths:
            - '{application}'
        default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

server.port: ${CONFIG_SERVER_PORT:8899}