spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GITHUB_URI}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PAT}
          clone-on-start: true
          timeout: 10
          skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT}/eureka

server.port: ${CONFIG_SERVER_PORT}