spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thural/quietspcae-config.git
          username: thural
          password: ${GITHUB_PAT}
          clone-on-start: true
          timeout: 10
          skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 8899