spring:
  application.name: reaction-service
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}

  data:
    mongodb:
      database: ${DB_NAME}
      uri: ${REACTION_DB_URI}
      replica-set-name: ${MONGO_REPLICASET_NAME}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

values:
    gateway:
      url: ${GATEWAY_URL}

server:
  port: ${REACTION_SERVICE_PORT}
