spring:
  application:
    name: reaction-service
    urls:
      frontend: "http://localhost:5000"

    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 600000 # 10 minutes
        refresh-token:
          expiration: 86400000 # one day
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8899/config-server}

  data:
    mongodb:
      database: ${DB_NAME}
      host: localhost
      port: ${REACTION_DB_PORT}
      username: ${DB_ROOT_USERNAME}
      password: ${DB_ROOT_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

values:
  gateway:
    url: ${GATEWAY_URL}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: ${REACTION_SERVICE_PORT}
